import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "../app/components/Home/Navbar";
import Footer from "./components/Footer";
import {ViewTransitions } from 'next-view-transitions'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Veyangoda Central College Past Student Association",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ViewTransitions>
      <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
    </ViewTransitions>
    
  );
}
